---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeploy
spec:
  minReadySeconds: 5
  replicas: 10
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: web
        version: v1.0
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:jdk17
          resources:
            limits:
              memory: 1000m
              cpu: 2000m
          ports:
            - containerPort: 8080