---
apiVersion: v1
kind: pod
metadata:
  name: test1
spec:
  containers:
    - name: alpine
      image: alpine:3.20
      resources:
        requests:
          cpu: 0.5
          memory: 100m
        limits:
          cpu: 1.0
          memory: 200m